export const GET_FILM_LIST = 'GET_FILM_LIST';
export const GET_BANNER_LIST = 'GET_BANNER_LIST';
export const SET_CHI_TIET_PHIM = 'SET_CHI_TIET_PHIM';
export const SET_CHI_TIET_PHONG_VE = 'SET_CHI_TIET_PHONG_VE';
export const DAT_VE = 'DAT_VE';
export const LAY_THONG_TIN_PHIM_THEO_MA = 'LAY_THONG_TIN_PHIM_THEO_MA';
export const DAT_VE_HOAN_TAT = 'DAT_VE_HOAN_TAT';
export const CHUYEN_TAB = 'CHUYEN_TAB';